### PR TITLE
feat: tf entry

### PR DESCRIPTION
**Pull request by m-muecke**

### CODE REVIEW

**Comment by krlmlr** [comment]
Thanks! What effect does subsetting have on a `tfd` or `tfb` vector? Is there an `NA` value (subsetting with `NA_integer_`)?

**Comment by m-muecke** [comment]
> Thanks! What effect does subsetting have on a `tfd` or `tfb` vector? Is there an `NA` value (subsetting with `NA_integer_`)?

Subsetting works like with a normal vector, where one can subset the curves with a single `[`:

``` r
library(tf)
#> 
#> Attaching package: 'tf'
#> The following objects are masked from 'package:stats':
#> 
#>     sd, var

t <- tf_rgp(10)
t[1]
#> tfd[1] on (0,1) based on 51 evaluations each
#> interpolation by tf_approx_linear 
#> [1]: (0.00,0.26);(0.02,0.32);(0.04,0.43); ...
t[1:3]
#> tfd[3] on (0,1) based on 51 evaluations each
#> interpolation by tf_approx_linear 
#> [1]: (0.00,0.26);(0.02,0.32);(0.04,0.43); ...
```

<sup>Created on 2024-01-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

or retrieve the values of the specific curve, i.e. get the evaluations with `[[`:

``` r
library(tf)
#> 
#> Attaching package: 'tf'
#> The following objects are masked from 'package:stats':
#> 
#>     sd, var

t <- tf_rgp(10)
t[[1]]
#>  [1]  0.80126778  0.79927459  0.81849334  0.83993241  0.83782329  0.90098856
#>  [7]  0.82769528  0.81794248  0.84243085  0.74732568  0.73861526  0.62645613
#> [13]  0.62206016  0.53464054  0.45902670  0.34880176  0.28917784  0.13921670
#> [19]  0.01586509 -0.12522979 -0.25582339 -0.42626596 -0.56578068 -0.71831591
#> [25] -0.87016759 -0.98558529 -1.15228514 -1.23107541 -1.30720092 -1.38784016
#> [31] -1.46460538 -1.51234306 -1.50938772 -1.51691048 -1.53675273 -1.47570328
#> [37] -1.46191381 -1.45156718 -1.31276733 -1.23273523 -1.12214184 -1.04369339
#> [43] -0.90945295 -0.74522694 -0.61874936 -0.48088807 -0.34985516 -0.21271918
#> [49]  0.01833114  0.13181152  0.25605475
```

<sup>Created on 2024-01-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by krlmlr** [comment]
Thanks. Would you like to extend the examples? Happy to merge then.

**Comment by krlmlr** [comment]
Thanks!

**Comment by m-muecke** [comment]
Cheers! Forgot to add a more extensive example for the tfb vector, will just add an example at a later stage.

**Pull request merged**
